name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: gcc.exe -D__DEBUG__ main.o  -o "Hello.exe" -L"D:/Dev-Cpp/lib"  -g3
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
